# The URL the site will be built for
base_url = "https://simlay.net"
title = "simlay"
description = "The home of simlay.net"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "zerm"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`)
style = "inline"

# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = "andromeeda"
#theme = "ayu-dark"
#theme = "aurora-x"

# 2. If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting page for the possible choices.
light_theme = "github-light"
dark_theme = "github-dark"

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
extra_themes = []

# Put all your custom variables here
[extra]

# Zerm
author = "Sebastian Imlay"
show_author = false
show_tags = true
show_categories = true
theme_color = "blue"
main_menu = [
    {url="/me/", name="me"},
]
logo_text = "simlay"
google_analytics = { enabled = true, id = "UA-44653605-1"}
goatcounter_code = "simlay"
read_more = "read more"
og_preview_img = "simlay.png"
mastodon_url = "https://hachyderm.io/@simlay"
#simlay_analytics = "E7B751699DC7"

# Link in logo. Default returns you to $BASE_URL.
#logo_home_link = "/"


